# Computing matrix (vector) products and higher powers using `numpy` and `sympy`
Let's start by importing the relevant packages

In [1]:
import numpy as np
import sympy as sy

## `numpy`
If we want to multiply two matrices or a matrix and a vector we can just use the operator `@` to do this.

In [3]:
A = np.array([[1,2,3], [4,5,6]])
x = np.array([[3], [4], [0]])
# Note that it is important that the dimensions of A and x match up in a way that makes sense
# We want x to be a column vector, so we need to initialise it as above
# We can check that their dimensions match up:
print(f"{A.shape=}")
print(f"{x.shape=}")

A.shape=(2, 3)
x.shape=(3, 1)


To multiply them we now just do the following:

In [4]:
b = A @ x
b

array([[11],
       [32]])

This works if you want to multiply any two matrices (provided their dimensions match up appropriately). If we have a square matrix then we can multiply it with itself as many times as we would like. If we want to compute a higher matrix power we can do this using a for loop or a custom function, but `numpy` has a built-in method called `np.linalg.matrix_power`. 
(Side fact: `numpy` uses parallelization under the hood of their functions so this is likely much faster than whatever we might quickly be able to code up using a foor loop.)

In [8]:
B = np.array([[1,2], [-1, 6]])
B

array([[ 1,  2],
       [-1,  6]])

In [10]:
C = np.linalg.matrix_power(B, 10) # inputs are (matrix, desired_power)
C

array([[-3010561, 13733006],
       [-6866503, 31321954]])

In sympy these things work very similarly:

In [15]:
A = sy.Matrix([[1,2,3], [4,5,6]])
x = sy.Matrix([[3], [4], [0]])

A@x

Matrix([
[11],
[32]])

In [16]:
B = sy.Matrix([[1,2], [-1, 6]])
B

Matrix([
[ 1, 2],
[-1, 6]])

If you want to compute a power of  a matrix in `sympy` you can do this by writing `B ** k` where `k` is the power you would like to compute:

In [18]:
B ** 10

Matrix([
[-3010561, 13733006],
[-6866503, 31321954]])

## WARNING!!!
If you have a `numpy` array `B` then `B ** k` will not compute the matrix power of `B` to the k-th power, but it will instead compute a matrix where you take the k-th power of every entry of B. As we will learn later this is not the same at all as computing the k-th power of a matrix (except for very special situations).

See below how the result is very different if we take a `numpy` array.

In [19]:
B = np.array([[1,2], [-1, 6]])
B ** 10

array([[       1,     1024],
       [       1, 60466176]])